'use strict';
const KEY = 'casa-al-dia-v1';
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => new Intl.NumberFormat('es-AR', {style:'currency',currency:'ARS',maximumFractionDigits:2}).format(v);
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const date = v => new Date(v+'T12:00:00').toLocaleDateString('es-AR');
const validDate = v => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) && !isNaN(new Date(v+'T12:00:00')) && new Date(v+'T12:00:00').toISOString().slice(0,10) === v;
const safeUrl = v => { try { const u = new URL(v); return ['https:','http:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } };
let state = {version:1,services:[],bills:[]};
function notify(message){ $('#notice').textContent = message; }
function validate(data){
 if(!data || data.version !== 1 || !Array.isArray(data.services) || !Array.isArray(data.bills)) throw Error('Formato de archivo inválido.');
 const services = data.services.map(s => { if(!s || typeof s.id !== 'string' || !s.id || typeof s.name !== 'string' || !s.name.trim()) throw Error('Servicio inválido.'); return {id:s.id,name:s.name.slice(0,80),url:safeUrl(s.url),username:typeof s.username === 'string' ? s.username.slice(0,150) : '',unit:['kWh','m³','GB','min'].includes(s.unit)?s.unit:''}; });
 if(new Set(services.map(s=>s.id)).size !== services.length) throw Error('Servicios duplicados.');
 const bills = data.bills.map(b => { if(!b || typeof b.id !== 'string' || !b.id || !services.some(s=>s.id===b.serviceId) || !validDate(b.due) || !/^\d{4}-(0[1-9]|1[0-2])$/.test(b.period) || typeof b.amount !== 'number' || !Number.isFinite(b.amount) || b.amount<0 || (b.consumption != null && (typeof b.consumption !== 'number' || !Number.isFinite(b.consumption) || b.consumption<0)) || (b.paidAt != null && !validDate(b.paidAt))) throw Error('Factura inválida.'); return {id:b.id,serviceId:b.serviceId,period:b.period,due:b.due,amount:b.amount,consumption:b.consumption??null,note:typeof b.note==='string'?b.note.slice(0,250):'',paidAt:b.paidAt??null}; });
 if(new Set(bills.map(b=>b.id)).size !== bills.length) throw Error('Facturas duplicadas.');
 return {version:1,services,bills,updatedAt:typeof data.updatedAt==='string' && !isNaN(Date.parse(data.updatedAt))?data.updatedAt:null};
}
function save(next){ try { next.updatedAt=new Date().toISOString(); localStorage.setItem(KEY,JSON.stringify(next)); state=next; render(); return true; } catch { notify('No se pudo guardar. Revisá el espacio y los permisos del navegador. Descargá un respaldo antes de cerrar.'); return false; } }
function status(b){ if(b.paidAt) return ['paid','Pagada']; const days=Math.round((new Date(b.due+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000); return days<0?['overdue','Vencida']:days===0?['soon','Vence hoy']:days<=7?['soon',`Vence en ${days} día${days===1?'':'s'}`]:['pending','Pendiente']; }
function summary(){ const pending=state.bills.filter(b=>!b.paidAt), overdue=pending.filter(b=>status(b)[0]==='overdue'), soon=pending.filter(b=>status(b)[0]==='soon'); $('#summary').innerHTML = `<div class="stat"><span>Total pendiente</span><strong>${money(pending.reduce((a,b)=>a+b.amount,0))}</strong><span>${pending.length} factura${pending.length===1?'':'s'} por pagar</span></div><div class="stat"><span>Próximos 7 días</span><strong>${soon.length}</strong><span>Incluye las que vencen hoy</span></div><div class="stat"><span>Vencidas</span><strong>${overdue.length}</strong><span>${overdue.length?'Revisar antes de pagar':'Sin pagos atrasados'}</span></div>`; }
function billHTML(b){ const s=state.services.find(s=>s.id===b.serviceId); const [kind,label]=status(b); const previous=state.bills.filter(x=>x.serviceId===b.serviceId && x.period<b.period).sort((a,b)=>b.period.localeCompare(a.period))[0]; const change=previous?.amount>0?((b.amount-previous.amount)/previous.amount*100):null;
 return `<article class="bill"><div class="bill-top"><div><h3>${esc(s.name)}</h3><div class="meta">Período ${esc(b.period.split('-').reverse().join('/'))}</div></div><div class="amount">${money(b.amount)}</div></div><span class="badge ${kind}">${label}</span><div>Vencimiento: <strong>${date(b.due)}</strong>${b.paidAt?` · Pagada el ${date(b.paidAt)}`:''}</div>${b.consumption!==null?`<p>Consumo: <strong>${esc(b.consumption)} ${esc(s.unit)}</strong></p>`:''}${change!==null?`<p class="meta">${change>=0?'+':''}${change.toFixed(1)}% respecto del período anterior registrado</p>`:''}${b.note?`<p>${esc(b.note)}</p>`:''}<div class="actions"><button class="small ${b.paidAt?'secondary':''}" data-action="pay" data-id="${esc(b.id)}">${b.paidAt?'Deshacer pago':'Marcar pagada'}</button><button class="secondary small" data-action="edit-bill" data-id="${esc(b.id)}">Editar</button><button class="text-button" data-action="delete-bill" data-id="${esc(b.id)}">Eliminar</button>${b.paidAt?`<button class="secondary small" data-action="message" data-id="${esc(b.id)}">Mensaje para WhatsApp</button>`:''}</div></article>`;
}
function list(bills,empty){return bills.length?bills.sort((a,b)=>a.due.localeCompare(b.due)).map(billHTML).join(''):`<div class="empty">${empty}</div>`;}
function render(){summary(); const filter=$('#filter').value; $('#bills').innerHTML=list(state.bills.filter(b=>filter==='all'||(filter==='paid'?!!b.paidAt:!b.paidAt)),'No hay facturas en esta vista. Registrá una para empezar.');
 $('#services').innerHTML=state.services.length?state.services.map(s=>`<article class="service"><h3>${esc(s.name)}</h3><div class="actions">${s.url?`<a class="button secondary small" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Abrir web</a>`:''}${s.username?`<button class="secondary small" data-action="copy-user" data-id="${esc(s.id)}">Copiar usuario</button>`:''}<button class="text-button" data-action="access" data-id="${esc(s.id)}">Contraseña</button><button class="text-button" data-action="edit-service" data-id="${esc(s.id)}">Editar</button><button class="text-button" data-action="delete-service" data-id="${esc(s.id)}">Eliminar</button></div></article>`).join(''):'<div class="empty">Agregá tu primer servicio con su enlace web.</div>';
}
function paymentMessage(b){
 const service=state.services.find(s=>s.id===b.serviceId);
 return `Hola, mamá 😊 Ya pagué ${service.name}.\n\nPeríodo: ${b.period.split('-').reverse().join('/')}\nImporte: ${money(b.amount)}\nFecha de pago: ${date(b.paidAt)}\nVencimiento de la factura: ${date(b.due)}\n\nEste pago ya quedó registrado. ✅`;
}
function openMessage(id){ const bill=state.bills.find(b=>b.id===id); if(!bill?.paidAt)return; $('#payment-message').value=paymentMessage(bill); $('#message-dialog').showModal(); }
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(text){ if(!text){notify('Primero ingresá el dato que querés copiar.');return;} try{await navigator.clipboard.writeText(text);notify('Copiado al portapapeles.');}catch{notify('El navegador no permitió copiar. Seleccioná el texto y copialo manualmente.');} }
function openBill(id){if(!state.services.length){notify('Agregá un servicio antes de registrar una factura.');$('#service-dialog').showModal();return;} const f=$('#bill-form');f.reset();f.elements.serviceId.innerHTML=state.services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');f.elements.id.value='';f.elements.period.value=today().slice(0,7);if(id){const b=state.bills.find(b=>b.id===id);for(const k of ['id','serviceId','period','due','amount','consumption','note']) f.elements[k].value=b[k]??'';}$('#bill-title').textContent=id?'Editar factura':'Registrar factura';$('#bill-dialog').showModal();}
async function init(){
 try{const data=localStorage.getItem(KEY);if(data)state=validate(JSON.parse(data));}catch{notify('No se pudieron leer los registros guardados. Restaurá un respaldo; el archivo original no se modificó.');}
 render();$('#filter').addEventListener('change',render);$('#new-bill').onclick=()=>openBill();$('#new-service').onclick=()=>{$('#service-form').reset();$('#service-form').elements.id.value='';$('#service-dialog').showModal();};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#access-dialog').addEventListener('close',()=>{$('#temporary-password').value='';});$('#copy-password').onclick=()=>copy($('#temporary-password').value);
 $('#service-form').onsubmit=e=>{e.preventDefault();const f=e.target, raw=f.elements.url.value.trim(),url=safeUrl(raw);if(raw&&!url){notify('El enlace debe comenzar con https:// o http://.');return;}const s={id:f.elements.id.value||crypto.randomUUID(),name:f.elements.name.value.trim(),url,username:f.elements.username.value.trim(),unit:f.elements.unit.value};if(!s.name)return;const next=structuredClone(state);const index=next.services.findIndex(x=>x.id===s.id);if(index<0)next.services.push(s);else next.services[index]=s;if(save(next))$('#service-dialog').close();};
 $('#bill-form').onsubmit=e=>{e.preventDefault();const f=e.target,old=state.bills.find(b=>b.id===f.elements.id.value),b={id:old?.id||crypto.randomUUID(),serviceId:f.elements.serviceId.value,period:f.elements.period.value,due:f.elements.due.value,amount:Number(f.elements.amount.value),consumption:f.elements.consumption.value===''?null:Number(f.elements.consumption.value),note:f.elements.note.value.trim(),paidAt:old?.paidAt??null};const next=structuredClone(state);if(old)next.bills[next.bills.findIndex(x=>x.id===old.id)]=b;else next.bills.push(b);try{validate(next);if(save(next))$('#bill-dialog').close();}catch(error){notify(error.message);}};
 document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const id=btn.dataset.id, action=btn.dataset.action,s=state.services.find(s=>s.id===id);if(action==='copy-user')return copy(s.username);if(action==='access'){$('#access-title').textContent=s.name;$('#access-dialog').showModal();return;}if(action==='edit-service'){const f=$('#service-form');for(const k of ['id','name','url','username','unit'])f.elements[k].value=s[k];$('#service-dialog').showModal();return;}if(action==='edit-bill')return openBill(id);if(action==='message')return openMessage(id);const next=structuredClone(state);if(action==='pay'){const b=next.bills.find(b=>b.id===id);b.paidAt=b.paidAt?null:today();}if(action==='delete-bill'){if(!confirm('¿Eliminar esta factura?'))return;next.bills=next.bills.filter(b=>b.id!==id);}if(action==='delete-service'){if(next.bills.some(b=>b.serviceId===id)){notify('Este servicio tiene facturas. Eliminá sus facturas antes de borrar el servicio.');return;}if(!confirm('¿Eliminar este servicio?'))return;next.services=next.services.filter(s=>s.id!==id);}if(save(next)&&action==='pay'&&next.bills.find(b=>b.id===id)?.paidAt)openMessage(id);});
 $('#backup').onclick=()=>download(state,'casa-respaldo.json');$('#copy-message').onclick=()=>copy($('#payment-message').value);$('#message-dialog').addEventListener('close',()=>{$('#payment-message').value='';});
 $('#restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=validate(JSON.parse(await file.text()));if(confirm('¿Reemplazar los registros de este navegador por el respaldo?'))if(save(data))notify('Respaldo restaurado.');}catch(error){notify(`No se restauró el archivo: ${error.message}`);}finally{e.target.value='';}};
}
init();
